### ISSUE TITLE
historical weekly projections?

### ISSUE THREAD

**Issue by hsharrison** [dadrivr/FantasyFootballAnalyticsR#18]
Just curious, I don't see it but I might be missing something. Do you have historical week-by-week projections? I think some of your analyses (e.g. weekly variability) would be more interesting looking at the deviation from weekly projection rather than the raw score. I'd be interested in exploring this myself but don't have the data. Thoughts?

**Comment by mac0904** [comment]
I'm not really sure how to use all this stuff. I was trying to learn it one night and followed instructions on the fantasy football analytics blog to link to his project. His site has the app that can be ran online without having to run it through GitHub (link below).


http://fantasyfootballanalytics.net/2014/07/fantasy-football-draft-optimizer-shiny-app-2014-update.html




Thanks,

Mac Crollman


Sent from my iPhone with Auto Correct - please excuse any Auto Correct "Fails"

On Oct 10, 2015, at 2:35 PM, Henry S. Harrison <notifications@github.com> wrote:

Just curious, I don't see it but I might be missing something. Do you have historical week-by-week projections? I think some of your analyses (e.g. weekly variability) would be more interesting looking at the deviation from weekly projection rather than the raw score. I'd be interested in exploring this myself but don't have the data. Thoughts?

**Comment by dadrivr** [comment]
Yes, you can download historical projections from this season using our Projections tool:
http://apps.fantasyfootballanalytics.net/projections

**Comment by hsharrison** [comment]
Ah, I missed that in the options. Any chance of making the weekly data available from previous seasons?

**Comment by dadrivr** [comment]
We didn't start collecting weekly projections until this season.
